library("quantmod")
library("tseries")
library("urca")

start <- as.Date("2018-02-02")
end <- as.Date("2020-02-02")
Data1 <- getSymbols("BTC-USD", src = "yahoo", from = start, to = end, auto.assign = FALSE)
Data2 <- getSymbols("LTC-USD", src = "yahoo", from = start, to = end, auto.assign = FALSE)
Data3 <- getSymbols("ETH-USD", src = "yahoo", from = start, to = end, auto.assign = FALSE)
p1 = unclass(Data1$'BTC-USD.Adjusted')
p2 = unclass(Data2$'LTC-USD.Adjusted')
p3 = unclass(Data3$'ETH-USD.Adjusted')
jotest=ca.jo(data.frame(p1,p2,p3), type="trace", K=2, ecdet="none", spec="longrun")
summary(jotest)
#таким образом искать возможные комбинации. вероятно, перебором в цикле...

plot(p1, type="l", xlab="p1", ylab="Backward-Adjusted Prices in USD", col="blue")
par(new=T)
plot(p2, type="l", axes=F, xlab="", ylab="", col="red")
par(new=F)
plot(p1, p2, xlab="p1 Backward-Adjusted Prices", ylab="p2 Backward-Adjusted Prices")
comb = comb = lm(p1~p2)
adf.test(comb$residuals, k=1)
comb = comb = lm(p2~p1)
adf.test(comb$residuals, k=1)
